---
layout: cv
title: Resume Garidon Hendricks
---
# Garidon Hendricks

<div id="webaddress">
| <a href="linkedin.com/in/garidon">My LinkedIn Page</a>
</div>

## Education

`B.S. in Business Management`
__Brigham Young University - Idaho__
- Minors in Business Analytics and Music
- Integrated Business Core: 
    - Part-owner/operator of a student-run business for 9 weeks that achieved $9k+ in revenue and $4k+ in operating profit
    - Created KPI visibility throughout the company by assembling and managing a consolidated 4DX dashboard
- Courses: Data Science Programming, Organizational Leadership, Professional Selling, Intro to Software Development, Financial Management


## Experience

`Program Assessment Coordinator, Pilot Program Coordinator`
__First Year Experience, BYU-Idaho__, Sept 2024 - Nov 2025; Rexburg, ID

- Gathered, interpreted, and visualized qualitative and quantitative data to help senior leadership make data-driven strategy decisions
- Affected change by presenting findings to senior program leadership
- Administered multiple pilot programs to develop future organizational initiatives
- Designed and delivered training content for 125 New Student Mentors 

`Session Coordinator`
__FSY (Youth Summer Camps)__, Seasonal, Summers 2024-2025; UT, SC, CO, NE, etc.
- Led and mentored hundreds of young adult counselors
- Ensured alignment to program goals for conferences of 700+ teens through adherence to policies and
procedures
- Mitigated 20+ emergency situations by partnering with full-time administrative staff 

`Data and Social Media Secretary - Volunteer Missionary`
__Brazil João Pessoa Mission__, Jan-July 2023; João Pessoa, Brazil
- Tracked and reported key performance indicators for 100+ missionaries weekly in Microsoft Excel
- Restructured inbound-lead management system to enable timely contact by correct representatives
- Managed social media advertising 


## Skills

- Python (scikit learn, pandas, letsplot)
- Microsoft Excel, PowerPoint, Word, and Teams
- GitHub
- Excellent written and verbal communication (public speaking)


## Foreign Languages
- Portuguese (fluent, 20 months immersive experience with native speakers)


<!-- ### Footer

Last updated: Nov 2025 -->